# ATENTION!! This file is used by Gitlab-CI

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: crud_ci
  username: kelvin
  password: kelvin
  host: 127.0.0.1

development:
  <<: *default

test:
  <<: *default
  database: realize_test

production:
  <<: *default
  database: realize_dev

short_urls_production:
  <<: *default
  database: realize_urls_production